version: "3.8"
services:
  vault:
    image: vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      # Use production values here – initialization will be manual
      VAULT_LOCAL_CONFIG: |
        {
          "listener": [{
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_cert_file": "/vault/config/vault.crt",
              "tls_key_file": "/vault/config/vault.key"
            }
          }],
          "storage": {
            "raft": {
              "path": "/vault/data",
              "node_id": "vault-node1"
            }
          },
          "ui": true,
          "audit": [{
            "file_path": "/vault/logs/audit.log",
            "log_raw": true
          }]
        }
    volumes:
      - ./vault/config:/vault/config
      - ./vault/logs:/vault/logs
      - vault_data:/vault/data
    cap_add:
      - IPC_LOCK
    command: "server"

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  vault_data:
  caddy_data:
  caddy_config:
