name: Build and Deploy Docs

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Docusaurus
        run: |
          npm install -g @docusaurus/init

      - name: Create docs directory and copy markdown files
        run: |
          mkdir -p website/docs
          rsync -av --include='*/' --include='*.md' --exclude='*' ./ website/docs/

      - name: Generate dynamic sidebar
        run: |
          python .github/scripts/generate_sidebar.py

      - name: Install dependencies
        run: |
          cd website
          npm install

      - name: Build Docusaurus site
        run: |
          cd website
          npm run build

      - name: Deploy to GitHub Pages
        env:
          GIT_USER: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd website
          npm run deploy
